# Start from a Java 17 base image
FROM eclipse-temurin:17-jdk-alpine

# Set working directory
WORKDIR /app

# Copy Maven build files
COPY pom.xml mvnw ./
COPY .mvn .mvn

# Copy source code
COPY src src

# Build the project
RUN ./mvnw clean package -DskipTests

# Set the jar name
ARG JAR_FILE=target/server.jar

# Expose port
EXPOSE 8080

# Run the jar
CMD ["java", "-jar", "target/server.jar"]
